# Generated by Django 5.0.7 on 2024-09-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcalendar', '0002_homework_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='event_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
