# Generated by Django 5.0.7 on 2024-09-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcalendar', '0003_homework_event_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='timings',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
