# Generated by Django 5.0.7 on 2024-10-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcalendar', '0004_homework_timings'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
