# Generated by Django 5.0.7 on 2024-10-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredentials',
            name='classcharts_session_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='usercredentials',
            name='classcharts_student_id',
            field=models.IntegerField(null=True),
        ),
    ]
